//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sep4_GroupX2Entities : DbContext
    {
        public Sep4_GroupX2Entities()
            : base("name=Sep4_GroupX2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<co2> co2 { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<device> devices { get; set; }
        public DbSet<humidity> humidities { get; set; }
        public DbSet<room> rooms { get; set; }
        public DbSet<temperature> temperatures { get; set; }
        public DbSet<warning> warnings { get; set; }
    }
}
