//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class room
    {
        public room()
        {
            this.co2 = new HashSet<co2>();
            this.humidities = new HashSet<humidity>();
            this.warnings = new HashSet<warning>();
            this.temperatures = new HashSet<temperature>();
        }
    
        public int id { get; set; }
        [Required]
        public string room_name { get; set; }
        public Nullable<int> device_id { get; set; }
    
        public virtual ICollection<co2> co2 { get; set; }
        public virtual device device { get; set; }
        public virtual ICollection<humidity> humidities { get; set; }
        public virtual ICollection<warning> warnings { get; set; }
        public virtual ICollection<temperature> temperatures { get; set; }
    }
}
